insert into tbl_categories(Category_ES,Category_EN) values ('Superintendente de Plataforma','Rig Superintendent')
insert into tbl_categories(Category_ES,Category_EN) values ('Especialista Tecnico de Perforacion','Senior Toolpusher')
insert into tbl_categories(Category_ES,Category_EN) values ('Inspector Tecnico de Perforacion','Tool Pusher')
insert into tbl_categories(Category_ES,Category_EN) values ('Perforador','Driller')
insert into tbl_categories(Category_ES,Category_EN) values ('Asistente de Perforador','Assistant Driller')
insert into tbl_categories(Category_ES,Category_EN) values ('Bombero de Perforacion','Pump Man')
insert into tbl_categories(Category_ES,Category_EN) values ('Chango','Derrick Man')
insert into tbl_categories(Category_ES,Category_EN) values ('Ayudante de Piso de Perforacion','Roughneck')
insert into tbl_categories(Category_ES,Category_EN) values ('Ayudante de Trabajos de Perforacion','Roustabout')
insert into tbl_categories(Category_ES,Category_EN) values ('Supervisor ROV','ROV Supervisor')
insert into tbl_categories(Category_ES,Category_EN) values ('Operador ROV','ROV Operator')
insert into tbl_categories(Category_ES,Category_EN) values ('Especialista Subsea','Senior Subsea Engineer')
insert into tbl_categories(Category_ES,Category_EN) values ('Ingeniero Subsea','Subsea Engineer')
insert into tbl_categories(Category_ES,Category_EN) values ('Asistente Subsea','Subsea Assistant')
insert into tbl_categories(Category_ES,Category_EN) values ('Jefe de Mantenimiento','Chief Engineer')
insert into tbl_categories(Category_ES,Category_EN) values ('Primer Ingeniero','First Engineer')
insert into tbl_categories(Category_ES,Category_EN) values ('Segundo Ingeniero','Second Engineer')
insert into tbl_categories(Category_ES,Category_EN) values ('Tercer Ingeniero','Third Engineer')
insert into tbl_categories(Category_ES,Category_EN) values ('Motorista','Motorman')
insert into tbl_categories(Category_ES,Category_EN) values ('Tornero','Lathe Operator')
insert into tbl_categories(Category_ES,Category_EN) values ('Soldador','Welder')
insert into tbl_categories(Category_ES,Category_EN) values ('Planeador de Mantenimiento','Maintenance Planner')
insert into tbl_categories(Category_ES,Category_EN) values ('Supervisor Electrico','Electrical Supervisor')
insert into tbl_categories(Category_ES,Category_EN) values ('Tecnico Electronico e Instrumentista','Electronic Instrument Technician')
insert into tbl_categories(Category_ES,Category_EN) values ('Asistente de Tec Electrnico e Instrument','Electronic Instrument Assistant')
insert into tbl_categories(Category_ES,Category_EN) values ('Electricista                            ','Electrician')
insert into tbl_categories(Category_ES,Category_EN) values ('Asistente de Electricista','Electrician Assistant')
insert into tbl_categories(Category_ES,Category_EN) values ('Tecnico en Informatica','Information Technology Technician')
insert into tbl_categories(Category_ES,Category_EN) values ('Tecnico Hidraulico','Hydraulic Technician')
insert into tbl_categories(Category_ES,Category_EN) values ('Asistente de Tecnico Hidraulico','Hydraulic Assistant')
insert into tbl_categories(Category_ES,Category_EN) values ('Mecanico','Rig Mechanic')
insert into tbl_categories(Category_ES,Category_EN) values ('Asistente de Mecanico','Rig Mechanic Assistant')
insert into tbl_categories(Category_ES,Category_EN) values ('Almacenista','Storekeeper')
insert into tbl_categories(Category_ES,Category_EN) values ('Asistente de Almacenista','Storekeeper Assistant')
insert into tbl_categories(Category_ES,Category_EN) values ('Capitan','Captain')
insert into tbl_categories(Category_ES,Category_EN) values ('Jefe de Cubierta','Chief Mate')
insert into tbl_categories(Category_ES,Category_EN) values ('Oficial de Dia','Day Mate')
insert into tbl_categories(Category_ES,Category_EN) values ('Especialista de Posicionamiento Dinamico','Senior DPO')
insert into tbl_categories(Category_ES,Category_EN) values ('Operador de Posicionamiento Dinamico','DPO')
insert into tbl_categories(Category_ES,Category_EN) values ('Oficial de Proteccion del Buque','Ship Security Officer')
insert into tbl_categories(Category_ES,Category_EN) values ('Mayordomo','Campboss')
insert into tbl_categories(Category_ES,Category_EN) values ('Medico','Medic')
insert into tbl_categories(Category_ES,Category_EN) values ('Supervisor de Proteccion Ambiental','Environmental Officer')
insert into tbl_categories(Category_ES,Category_EN) values ('Operador de Grua','Crane Operator')
insert into tbl_categories(Category_ES,Category_EN) values ('Asistente de Operador de Grua','Crane Operator Assistant')
insert into tbl_categories(Category_ES,Category_EN) values ('Oficial de Operaciones Aereas','Helicopter Landing Officer')
insert into tbl_categories(Category_ES,Category_EN) values ('Tecnico Despachador de Combustible','Helicopter Fuel Dispatcher')
insert into tbl_categories(Category_ES,Category_EN) values ('Bombero Contraincendio','Firefighter')
insert into tbl_categories(Category_ES,Category_EN) values ('Radio Operador','Radio Operator')
insert into tbl_categories(Category_ES,Category_EN) values ('Supervisor de Pintura','Painter Supervisor')
insert into tbl_categories(Category_ES,Category_EN) values ('Pintor','Painter')
insert into tbl_categories(Category_ES,Category_EN) values ('Andamiero','Scaffolder')
insert into tbl_categories(Category_ES,Category_EN) values ('Contramaestre','Bosun')
insert into tbl_categories(Category_ES,Category_EN) values ('Marinero','Sea Man')
insert into tbl_categories(Category_ES,Category_EN) values ('Supervisor en Seguridad y Salud Ocupnal ','Rig Safety and Training Coordinator')
